# Site settings
title: Chenyu Zhao
SEOTitle: Chenyu Zhao | GitHub Portfolio
header-img: img/home-bg.jpg
email: zhaochenyu.2109@gmail.com
description: "PhD @ OSU | Welding Engineering Program, MSE | Java Full-Stack Developer"
keyword: "Chenyu Zhao, PhD, Welding Engineering, Material Science and Engineering, Manufacturing, Full-Stack Web Developer, Java, OSU"
url: "https://zhao-chenyu.github.io"
baseurl: ""
github_repo: "https://github.com/Zhao-chenyu/Zhao-chenyu.github.io.git"

# Sidebar settings
sidebar: true
sidebar-about-description: "PhD @ OSU | Welding Engineering Program, MSE | Java Full-Stack Developer"
sidebar-avatar: /img/my-avatar.jpg

# SNS settings
RSS: false
github_username: Zhao-chenyu

# Comments and analytics (disabled)
gitalk:
  enable: false

ba_track_id: ""
ga_track_id: ""
ga_domain: ""

# Featured Tags & PWA
featured-tags: false
featured-condition-size: 1

chrome-tab-theme-color: "#000000"
service-worker: true

# Friends (external links)
friends: [
  {
    title: "GitHub Home",
    href: "https://github.com/Zhao-chenyu"
  },{
    title: "Google Scholar",
    href: "https://scholar.google.com/citations?user=l73N_C4AAAAJ&hl=zh-CN"
  },{
    title: "LinkedIn",
    href: "https://www.linkedin.com/in/chenyuzhao78/"
  }
]

# Build settings
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
